language: java

jdk:
  - oraclejdk8
  - openjdk8

addons:
  sonarcloud:
    organization: "svendiedrichsen-github"

script:
  -|
    if [ $TRAVIS_BRANCH == "master" && $TRAVIS_PULL_REQUEST == "false" ]; then
      mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package cobertura:cobertura coveralls:report
    else
      mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package cobertura:cobertura coveralls:report sonar:sonar
    fi
