language: java

jdk:
  - openjdk8
  - oraclejdk11
  - openjdk11

git:
  depth: false

addons:
  sonarcloud:
    organization: "svendiedrichsen-github"

script:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package org.jacoco:jacoco-maven-plugin:report coveralls:report; fi'
  -
jobs:
  exclude:
    - jdk: openjdk8
      script:
      - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package org.jacoco:jacoco-maven-plugin:report coveralls:report sonar:sonar; fi'

