language: java

jdk:
  - oraclejdk8
  - openjdk8

addons:
  sonarcloud:
    organization: "svendiedrichsen-github"

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package cobertura:cobertura coveralls:report sonar:sonar
