name: Build

on:
  schedule:
    - cron: "15 0 * * *"
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: build and analyse
    runs-on: ubuntu-20.04
    env:
      MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Cache pom dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            node/
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build
        run: >
          ./mvnw $MAVEN_CLI_OPTS
          -Pcoverage
          dependency:go-offline
          clean verify
