name: Build

on:
  schedule:
    - cron: "15 0 * * *"
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: build and analyse
    runs-on: ubuntu-20.04
    env:
      MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
          cache: 'maven'
      - name: Build
        run: >
          ./mvnw $MAVEN_CLI_OPTS
          -Pcoverage
          clean verify
      - name: Analyse with SonarCloud
        if: ${{ github.event_name != 'pull_request' || (github.event.pull_request.head.repo.full_name == github.repository && github.actor != 'dependabot[bot]') }}
        run: >
          ./mvnw $MAVEN_CLI_OPTS
          -Pcoverage
          verify
          sonar:sonar
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.organization=focus-shift
          -Dsonar.projectKey=focus-shift_jollyday
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
